# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
desc "Deploy new beta"
  
  lane :beta do
  changelog = File.read("./changelog.txt")

  increment_build_number(
    build_number: latest_testflight_build_number + 1,
    xcodeproj: "OpenChargeApp.xcodeproj",
  )

  build_app(scheme: "OpenChargeApp")

  upload_to_testflight(
    username: "nchatharoo@icloud.com",
    app_identifier: "com.nchatharoo.OpenChargeApp",
             changelog: changelog
  )
end

end
